/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GitManu;

public class App {
    public static void main(String[] args) {
 System.out.println(Sumador.sumar (15f,4f));
}
}
