/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GitManu;

public class NewMain {
    public static void main(String[] args) {
 System.out.println(Restador.restar (15f,4f));
}
}
